#!/bin/bash

# Update package information
sudo apt update

# Upgrade installed packages
sudo apt upgrade -y

# Clean up unnecessary packages
sudo apt autoremove -y

# Clean up cached package data
sudo apt clean

echo "Update and upgrade complete."